"use client";
import React, { useState, useEffect } from 'react';
import AntScene from '@/components/ui/AntScene';
import { motion } from 'framer-motion';

const WORDS = ["SABRP", "PHOTO", "APPS", "TOOLS", "ANT"];

export default function AntShowcasePage() {
    const [currentWordIdx, setCurrentWordIdx] = useState(0);

    useEffect(() => {
        const interval = setInterval(() => {
            setCurrentWordIdx((prev) => (prev + 1) % WORDS.length);
        }, 4000);
        return () => clearInterval(interval);
    }, []);

    return (
        <main className="min-h-screen bg-[#050505] text-white selection:bg-white/20">
            {/* Hero Section */}
            <section className="relative h-screen flex flex-col items-center justify-center overflow-hidden">
                <div className="z-10 text-center px-4 pointer-events-none">
                    <motion.h1
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="text-4xl md:text-6xl font-black mb-4 tracking-tighter"
                    >
                        ANT PARTICLE <span className="text-[#EDEDED]">ENGINE</span>
                    </motion.h1>
                    <motion.p
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        transition={{ delay: 0.2 }}
                        className="text-white/40 text-lg md:text-xl max-w-2xl mx-auto"
                    >
                        A high-performance PIXI.js powered particle system that forms words and shapes dynamically.
                    </motion.p>
                </div>

                {/* The Ant Scene */}
                <AntScene
                    text={WORDS[currentWordIdx]}
                    contained={false}
                />

                <div className="absolute bottom-10 left-1/2 -translate-x-1/2 animate-bounce opacity-20">
                    <div className="w-6 h-10 border-2 border-white/20 rounded-full flex justify-center p-1">
                        <div className="w-1.5 h-1.5 bg-white/40 rounded-full" />
                    </div>
                </div>
            </section>

            {/* Info Section */}
            <section className="relative py-20 bg-black/50 border-y border-white/5">
                <div className="max-w-4xl mx-auto px-10 grid md:grid-cols-3 gap-12 text-center">
                    <div>
                        <h2 className="text-xl font-bold mb-2 text-white/80">Bezier Paths</h2>
                        <p className="text-white/40 text-sm leading-relaxed">
                            Each ant follows a randomized cubic Bezier curve to its target pixel.
                        </p>
                    </div>
                    <div>
                        <h2 className="text-xl font-bold mb-2 text-white/80">Procedural Scurry</h2>
                        <p className="text-white/40 text-sm leading-relaxed">
                            A noise-based vibration effect simulates realistic insect behavior.
                        </p>
                    </div>
                    <div>
                        <h2 className="text-xl font-bold mb-2 text-white/80">Pixel Sampling</h2>
                        <p className="text-white/40 text-sm leading-relaxed">
                            Particles are generated by sampling pixel data from any text or image.
                        </p>
                    </div>
                </div>
            </section>

            {/* Footer */}
            <footer className="py-20 text-center border-t border-white/5">
                <p className="text-white/20 text-sm">Built with PIXI.js & Next.js</p>
            </footer>
        </main>
    );
}
